name: Validate SIP

on:
  pull_request:
    paths:
      - "SIPS/**"

jobs:
  validate:
    name: Validate SIPs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/validate
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - name: Get Yarn version
        run: echo "::set-output name=YARN_VERSION::$(yarn --version)"
        id: yarn-version
      - run: yarn install --immutable
      - run: yarn build
      - name: Validate all SIPs
        run: yarn validate ../../SIPS/**
